name: PHPUnitWorkflow

on: [push]

jobs:
  #ID of this job. You see it on the actions page in Github and uses it for referencing in other jobs
  PHPUnit-Run:
    #OS of the VM that will be used to run the test
    runs-on: ubuntu-latest

    steps:
      #checks out the code
    - name: Check-out master branch
      uses: actions/checkout@v3
    
      #used to leverage composer CLI
    - name: Install composer CLI
      uses: php-actions/composer@v6

      #run phpunit
    - name: Run PHP unit tests
      uses: php-actions/phpunit@v3
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        #shows an itemized list of tests run
        args: --testdox

    - name: Hello World
      uses: phwes/simple_hello_world@v1
